name: Build & Update Backend Image

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: contactly-backend
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend repo
      uses: actions/checkout@v4

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build & Push image
      run: |
        docker build -t $DOCKER_USERNAME/$IMAGE_NAME:${{ github.sha }} .
        docker push $DOCKER_USERNAME/$IMAGE_NAME:${{ github.sha }}

    # GitOps step — update infra repo image tag
    - name: Checkout infra repo
      uses: actions/checkout@v4
      with:
        repository: Codewith-Mohit/Contactly-Infra
        token: ${{ secrets.GH_PAT }}
        path: infra

    - name: Update image tag in values.yaml
      run: |
        cd infra/apps/backend
        sed -i "s/tag:.*/tag: ${GITHUB_SHA}/" values.yaml

    - name: Commit & Push changes
      run: |
        cd infra
        git config user.name "github-actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update backend image to ${GITHUB_SHA}"
        git push